# CMake generated Testfile for 
# Source directory: /workspaces/ecc/relic/test
# Build directory: /workspaces/ecc/relic/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_err "/workspaces/ecc/relic/bin/test_err")
set_tests_properties(test_err PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;14;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_bn "/workspaces/ecc/relic/bin/test_bn")
set_tests_properties(test_bn PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;18;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_dv "/workspaces/ecc/relic/bin/test_dv")
set_tests_properties(test_dv PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;22;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_fp "/workspaces/ecc/relic/bin/test_fp")
set_tests_properties(test_fp PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;26;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_fpx "/workspaces/ecc/relic/bin/test_fpx")
set_tests_properties(test_fpx PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;30;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_fb "/workspaces/ecc/relic/bin/test_fb")
set_tests_properties(test_fb PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;34;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_fbx "/workspaces/ecc/relic/bin/test_fbx")
set_tests_properties(test_fbx PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;38;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_ep "/workspaces/ecc/relic/bin/test_ep")
set_tests_properties(test_ep PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;42;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_epx "/workspaces/ecc/relic/bin/test_epx")
set_tests_properties(test_epx PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;46;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_eb "/workspaces/ecc/relic/bin/test_eb")
set_tests_properties(test_eb PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;50;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_ed "/workspaces/ecc/relic/bin/test_ed")
set_tests_properties(test_ed PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;54;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_ec "/workspaces/ecc/relic/bin/test_ec")
set_tests_properties(test_ec PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;58;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_pc "/workspaces/ecc/relic/bin/test_pc")
set_tests_properties(test_pc PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;62;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_pp "/workspaces/ecc/relic/bin/test_pp")
set_tests_properties(test_pp PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;66;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_md "/workspaces/ecc/relic/bin/test_md")
set_tests_properties(test_md PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;70;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_cp "/workspaces/ecc/relic/bin/test_cp")
set_tests_properties(test_cp PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;74;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_mpc "/workspaces/ecc/relic/bin/test_mpc")
set_tests_properties(test_mpc PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;78;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_rand "/workspaces/ecc/relic/bin/test_rand")
set_tests_properties(test_rand PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;81;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
add_test(test_core "/workspaces/ecc/relic/bin/test_core")
set_tests_properties(test_core PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ecc/relic/test/CMakeLists.txt;10;add_test;/workspaces/ecc/relic/test/CMakeLists.txt;82;ADD_MODULE;/workspaces/ecc/relic/test/CMakeLists.txt;0;")
